const fmtDate = (d) => {
  if (!d) return ''
  const dt = new Date(d)
  const day = String(dt.getDate()).padStart(2, '0')
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  return `${day}-${months[dt.getMonth()]}-${dt.getFullYear()}`
}

const fmtDateTime = (d) => {
  if (!d) return ''
  const dt = new Date(d)
  const day = String(dt.getDate()).padStart(2, '0')
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  return `${day}-${months[dt.getMonth()]}-${dt.getFullYear()} ${dt.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}`
}

const fmtTimeOnly = (d) => d ? new Date(d).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }) : ''

const calcDuration = (login, logout) => {
  if (!login || !logout) return 'Running'
  const ms = new Date(logout) - new Date(login)
  const hours = Math.floor(ms / 3600000)
  const minutes = Math.floor((ms % 3600000) / 60000)
  return `${hours}h${minutes}m`
}

const styles = `
  #print-report { display: none; }
  @media print {
    @page { margin: 0; }
    body * { visibility: hidden; }
    #print-report, #print-report * { visibility: visible; }
    #print-report { 
      display: block; 
      position: absolute; 
      left: 0; 
      top: 0; 
      width: 100%; 
      background: white;
      padding: 20px;
      font-family: 'Courier New', 'Monaco', monospace;
    }
    .print-container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
    }
    .no-print { display: none !important; }
  }
`

import { createPortal } from 'react-dom'

export default function PrintReport({ histories }) {
  const user = JSON.parse(localStorage.getItem('user') || '{}')
  const startDate = histories.length ? histories[histories.length - 1].login_at : new Date()
  const endDate = histories.length ? histories[0].login_at : new Date()
  const activeSessions = histories.filter(h => !h.logout_at).length
  const totalUsers = histories.length
  const avgHours = histories.reduce((sum, h) => {
    if (h.login_at && h.logout_at) {
      const ms = new Date(h.logout_at) - new Date(h.login_at)
      return sum + (ms / 3600000)
    }
    return sum
  }, 0)
  const avgHoursDisplay = totalUsers > 0 ? (avgHours / totalUsers).toFixed(1) : '0'

  return (
    <>
      <style>{styles}</style>
      <button
        type="button"
        onClick={() => window.print()}
        className="no-print inline-flex items-center gap-1.5 bg-teal-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-teal-700 transition-colors shadow-sm"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
        </svg>
        Print Report
      </button>
      {createPortal(
        <div id="print-report">
          <div className="print-container">
            {/* Header */}
            <div className="text-center border-b-2 border-gray-800 pb-4 mb-4">
              <div className="text-xl font-bold uppercase tracking-wide">Sweet Coffee Shop</div>
              <div className="text-sm">No. 12, Street 271, Phnom Penh, Cambodia</div>
              <div className="text-sm">Tel: 012 345 678 | POS System</div>
              <div className="text-lg font-bold mt-3">USER LOGIN REPORT</div>
              <div className="border-t border-gray-400 mt-3"></div>
            </div>

            {/* Report Info */}
            <div className="mb-4 text-sm">
              <div className="grid grid-cols-2 gap-2 mb-2">
                <div><span className="font-bold">Date Range:</span> {fmtDate(startDate)} → {fmtDate(endDate)}</div>
                <div><span className="font-bold">Generated:</span> {fmtDateTime(new Date())}</div>
                <div><span className="font-bold">Generated By:</span> {user.name || 'Admin'}</div>
              </div>
            </div>

            {/* Table */}
            <div className="mb-4">
              <table className="w-full border-collapse border border-black text-sm">
                <thead>
                  <tr className="bg-gray-200">
                    <th className="border border-black px-3 py-2 text-left font-bold">ID</th>
                    <th className="border border-black px-3 py-2 text-left font-bold">User</th>
                    <th className="border border-black px-3 py-2 text-left font-bold">Login</th>
                    <th className="border border-black px-3 py-2 text-left font-bold">Logout</th>
                    <th className="border border-black px-3 py-2 text-left font-bold">Status</th>
                    <th className="border border-black px-3 py-2 text-left font-bold">Duration</th>
                  </tr>
                </thead>
                <tbody>
                  {histories.map((h, idx) => (
                    <tr key={h.id}>
                      <td className="border border-black px-3 py-2">{String(idx + 1).padStart(2, '0')}</td>
                      <td className="border border-black px-3 py-2">{h.user?.name || '—'}</td>
                      <td className="border border-black px-3 py-2">{fmtTimeOnly(h.login_at) || '—'}</td>
                      <td className="border border-black px-3 py-2">{h.logout_at ? fmtTimeOnly(h.logout_at) : '—'}</td>
                      <td className="border border-black px-3 py-2">
                        {h.logout_at ? 'Closed' : 'Active'}
                      </td>
                      <td className="border border-black px-3 py-2">{calcDuration(h.login_at, h.logout_at)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Summary Footer */}
            <div className="border-t border-gray-800 pt-3 mt-3">
              <div className="text-sm">
                <div className="flex justify-between mb-1">
                  <span className="font-bold">Total Users Login Today :</span>
                  <span>{totalUsers}</span>
                </div>
                <div className="flex justify-between mb-1">
                  <span className="font-bold">Active Sessions :</span>
                  <span>{activeSessions}</span>
                </div>
                <div className="flex justify-between mb-1">
                  <span className="font-bold">Total Working Hours Avg :</span>
                  <span>{avgHoursDisplay}h</span>
                </div>
              </div>
            </div>

            {/* Footer Line */}
            <div className="text-center text-xs text-gray-500 mt-4 pt-2 border-t border-gray-300">
              © {new Date().getFullYear()} Sweet Coffee Shop - All Rights Reserved
            </div>
          </div>
        </div>,
        document.body
      )}
    </>
  )
}